ExpensesManagementProject/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace ExpensesManagementProject.Models
{
    public class Expense
    {
        public int ID { get; set; }

        // user ID from AspNetUser table.
        public string OwnerID { get; set; }
        public string FullName { get; set; }
        public int Cost { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime PaymentDate { get; set; }
        public string Secret { get; set; }
        public ExpContactStatus Status { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        //public int TotalSum { get; set; }
    }
        public enum ExpContactStatus
    {
        Submitted,
        Approved,
        Rejected
    }
}

ExpensesManagementProject/Controllers/ExpenseController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web.Mvc;
using ExpensesManagementProject.DAL;
using ExpensesManagementProject.Models;
using PagedList;

namespace ExpensesManagementProject.Controllers
{
    [Authorize]
    public class ExpenseController : Controller
    {
        private ProjectContext db = new ProjectContext();
        // GET: Expense
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page 
                                                                        //DateTime DateIn, DateTime DateOut
                                                                                                            )
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "cost_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "cost_asc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            string userId = null;

            var claimsIdentity = (ClaimsIdentity)User.Identity;

            var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            if (userIdClaim != null)
            {
                userId = userIdClaim.Value;
            }
            var expenses = from s in db.Expenses
                           where s.OwnerID == userId
                           select s;
            var TotalCost = 0;
            if (expenses.Count() != 0)
            {
                TotalCost = expenses.Sum(x => x.Cost);
            }
            var incomes = from s in db.Incomes
                          where s.OwnerID == userId
                          select s;
            var TotalWorth = 0;
            if (incomes.Count() != 0)
            {
                TotalWorth = incomes.Sum(x => x.Worth);
                ViewBag.TotalW = TotalWorth;
            }
            else ViewBag.TotalW = TotalWorth;
            var Minus = Math.Abs(TotalWorth - TotalCost);
            ViewBag.Difference = Minus;
            if (TotalWorth > 0)
            {
                int percentComplete = (int)Math.Round((double)(100 * Minus) / TotalWorth);
                ViewBag.Percentage = percentComplete;
                ViewBag.OK = 1;
            }
            else ViewBag.OK = 0;
            if (!String.IsNullOrEmpty(searchString))
            {
                expenses = expenses.Where(s => s.FullName.Contains(searchString));
            }
            //if(DateIn != null && DateOut != null)
            //{
            //    expenses = expenses.Where(s => s.PaymentDate >= DateIn
            //                                && s.PaymentDate <= DateOut);
            //}
            if (expenses.Count() != 0)
            {
                var TotalC = expenses.Sum(x => x.Cost);
                ViewBag.TotalS = TotalC;
            }
            else ViewBag.TotalS = 0;
            switch (sortOrder)
            {
                case "cost_desc":
                    expenses = expenses.OrderByDescending(s => s.Cost);
                    break;
                case "Date":
                    expenses = expenses.OrderBy(s => s.PaymentDate);
                    break;
                case "cost_asc":
                    expenses = expenses.OrderBy(s => s.Cost);
                    break;
                default:
                    expenses = expenses.OrderByDescending(s => s.PaymentDate);
                    break;
            }
            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(expenses.ToPagedList(pageNumber, pageSize));
        }

        // GET: Expense/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expense/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expense/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FullName,Cost,PaymentDate")] Expense expense)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string userId = null;

                    var claimsIdentity = (ClaimsIdentity)User.Identity;

                    var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
                    if (userIdClaim != null)
                    {
                        userId = userIdClaim.Value;
                    }
                    expense.OwnerID = userId;//Membership.GetUser(User.Identity.Name).;
                    db.Expenses.Add(expense);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(expense);
        }

        // GET: Expense/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expense/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FullName,Cost,PaymentDate")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                string userId = null;

                var claimsIdentity = (ClaimsIdentity)User.Identity;

                var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
                if (userIdClaim != null)
                {
                    userId = userIdClaim.Value;
                }
                expense.OwnerID = userId;//Membership.GetUser(User.Identity.Name).;
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        // GET: Expense/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expense/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpensesManagementProject/Controllers/IncomeController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web.Mvc;
using ExpensesManagementProject.DAL;
using ExpensesManagementProject.Models;
using PagedList;

namespace ExpensesManagementProject.Controllers
{
    [Authorize]
    public class IncomeController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Income
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "worth_asc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            string userId = null;

            var claimsIdentity = (ClaimsIdentity)User.Identity;

            var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            if (userIdClaim != null)
            {
                userId = userIdClaim.Value;
            }
            var incomes = from s in db.Incomes
                          where s.OwnerID == userId
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                incomes = incomes.Where(s => s.FullName.Contains(searchString)); 
            }
            if (incomes.Count() != 0)
            {
                var TotalWorth = incomes.Sum(x => x.Worth);
                ViewBag.CurrentSum = TotalWorth;
            }
            else ViewBag.CurrentSum = 0;
            switch (sortOrder)
            {
                case "name_desc":
                    incomes = incomes.OrderByDescending(s => s.Worth);
                    break;
                case "Date":
                    incomes = incomes.OrderBy(s => s.WageDate);
                    break;
                case "worth_asc":
                    incomes = incomes.OrderBy(s => s.Worth);
                    break;
                default:
                    incomes = incomes.OrderByDescending(s => s.WageDate);
                    break;
            }
            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(incomes.ToPagedList(pageNumber, pageSize));
        }
        // GET: Income/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // GET: Income/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Income/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FullName,Worth,WageDate")] Income income)
        {
            if (ModelState.IsValid)
            {
                string userId = null;

                var claimsIdentity = (ClaimsIdentity)User.Identity;

                var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
                if (userIdClaim != null)
                {
                    userId = userIdClaim.Value;
                }
                income.OwnerID = userId;
                db.Incomes.Add(income);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(income);
        }

        // GET: Income/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // POST: Income/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FullName,Worth,WageDate")] Income income)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string userId = null;

                    var claimsIdentity = (ClaimsIdentity)User.Identity;

                    var userIdClaim = claimsIdentity.Claims.SingleOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
                    if (userIdClaim != null)
                    {
                        userId = userIdClaim.Value;
                    }
                    income.OwnerID = userId;//Membership.GetUser(User.Identity.Name).;
                    db.Entry(income).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(income);
        }

        // GET: Income/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // POST: Income/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Income income = db.Incomes.Find(id);
            db.Incomes.Remove(income);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpensesManagementProject/Views/Expense/Create.cshtml
@model ExpensesManagementProject.Models.Expense

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Expense</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpensesManagementProject/Views/Expense/Delete.cshtml
@model ExpensesManagementProject.Models.Expense

@{
    ViewBag.Title = "Delete";
}

<h2>Remove</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

    </dl>
    <h4>Are you sure you want to remove this?</h4>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="YES, remove it !" class="btn btn-default" /> |
            @Html.ActionLink("NO, back to List", "Index")
        </div>
    }
</div>

ExpensesManagementProject/Views/Expense/Details.cshtml
@model ExpensesManagementProject.Models.Expense

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExpensesManagementProject/Views/Expense/Edit.cshtml
@model ExpensesManagementProject.Models.Expense

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExpensesManagementProject/Views/Expense/Index.cshtml
@model PagedList.IPagedList<ExpensesManagementProject.Models.Expense>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Expenses";
}

<h2>Expenses</h2>

<p>
    @Html.ActionLink("Add New", "Create")
</p>
@using (Html.BeginForm("Index", "Expense", FormMethod.Get))
{
<p>
    Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
    <input type="submit" value="Search" /> |
    @Html.ActionLink("Back to full List", "Index")
    @Html.TextBox("DateIn")
    @Html.TextBox("DateOut")
    @*<div class="form-group">
            @Html.LabelFor(model => model.DateIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateIn, "", new { @class = "text-danger" })
            </div>
        </div>*@
</p>
}
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            @Html.ActionLink("Cost (ron)", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("PaymentDate", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Remove", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

<h4>Total Cost: @ViewBag.TotalS RON</h4>
<br>


Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount



@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

@if (@ViewBag.OK == 1)
{
    <h4>Total savings: @ViewBag.Difference RON / @ViewBag.TotalW RON (@ViewBag.Percentage %)</h4>
}
else
{
    <h5> @Html.ActionLink("Add", "Create", "Income") a source of Income to see your Savings.</h5>
}